### ISSUE TITLE
Change from "todo" to another name - everywhere in app

### ISSUE THREAD

**Issue by jamespro** [jamespro/boomshark#16]
Naming things -- These items are not going to be "todo"s . So what is it?
1) database 2) collection
Also, the URLs would go along with that I assume  e.g. https://boomshark.herokuapp.com/todos
would change to /posts or /whatevers
and the Model, and a bunch of stuff

* projects?
* booms? sharks? Lol mostly kidding

Also: I had success before when I was changing this project from "todo" to making a list of "events". I found that with MongoDB, if you change the name of the database or collection, it just automagically creates them. So in that DB_STRING, if we change "todo" to a new database name in that string, it doesn't error, it should just create it

**Comment by justytho** [comment]
I think this one can be closed since I updated the project name is the  package.json all of these seem to be resolved (except the comment in controllers/profile.ejs but I think we can delete that file also?
