### ISSUE TITLE
Login Page - Styling

### ISSUE THREAD

**Issue by jamespro** [jamespro/boomshark#20]
URL: https://boomshark.herokuapp.com/login

I think this page needs Styling. Check the mockups that have been made and style it up!

So I'm labeling this mainly a frontend task.

Does it also need functionality? If login needs functionality, please create another ticket for that aspect.

**Comment by justytho** [comment]
Marking this one resolved, not sure who to give credit to one this one, but someone has already taken care of this so I'm closing this issue out.
