### ISSUE TITLE
Bug: Design: When resizing window smaller, form goes outside border

### ISSUE THREAD

**Issue by jamespro** [jamespro/boomshark#43]
![image](https://user-images.githubusercontent.com/1588016/117080872-b1da0400-ad0c-11eb-886e-8895d864131d.png)

Browser: Chrome
OS: Mac

How to recreate: I am on the profile page. I made the window smaller. 
* The input fields extend beyond the borders
* and/or the borders shrink too small such that the input fields go outside

**Comment by justytho** [comment]
Some weird stuff going on here for the .card class styling due to the way the <form> tag and .form-parent class were styled. I was able to improve this and get it closer to the intended design but it might not be pretty on mobile.

**Comment by jamespro** [comment]
It looks good on desktop when I checked it. I have not tested on mobile.
